### ISSUE TITLE
No summery on formdata.md (thankyou page)

### ISSUE THREAD

**Issue by fugo** [pmoreno-rodriguez/grav-theme-mundana#14]
I tried the contact form, but I have some problems.

The summery shows up in the email but not on the thankyou page (formdata.md).  
the ``body: '{% include ''forms/data.html.twig'' %}'`` code should do this?

I use data manger plugin and can see the form is working.   
On the thankyou page is only one sentence:
> Here is the summary of what you wrote to us:

Can I translate this? Site runs not in EN.

Thank you

**Comment by pmoreno-rodriguez** [comment]
Hi @fugo.
I've seen this [PR](https://github.com/getgrav/grav-plugin-form/issues/569) in the Form Plugin issues. Maybe it could be related with this behaviour. I will investigate how to fix it. 

On the other hand, I'll add the `thankyou` page to demo content, soon. The `Here is the summary of what you wrote to us:` sentence is from Form plugin and it is translated in its languages.yaml file, it will displayed in language defined in your system configuration.

**Comment by fugo** [comment]
Hi @pmoreno-rodriguez  
Sorry, I forget to set the default language, now it's translated.  
>  … I will investigate how to fix it.

Thank you :+1:  I use wit another site the *[Darkquark theme*](https://github.com/HeavyWolfPL/grav-theme-darkquark), with that it works.  

For working with the data from the form I need labels, so I put them in your form.  
I like your nice contact page so I use ``custom.css``to hide te labels:
```css
/* Custom CSS */
label.form-label {
	display: none !important;
}
```  
If anyone need this.

**Comment by fugo** [comment]
I found the way to get this to work.
In ``contact.md`` I deleted ``reset: true``. I also activated twig and no cache. 

```yaml
---
…
        display: /thankyou
        reset: true     <––  I removed this
…
     process:
        ip:
            label: 'User IP'
…
title: Kontakt
process:
    markdown: true
    twig: true
cache_enable: false
metadata:
…
---
```

I think we can close this issue, :thinking:
