### ISSUE TITLE
sc-alert class light wrong color

### ISSUE THREAD

**Issue by fugo** [pmoreno-rodriguez/grav-theme-mundana#15]
By using in ``[sc-alert]`` the class ``light`` the text color is **white** and then invisible.  
I found in theme.css and theme.min.css the wrong declarion and changed it to ``color: #818182;``.

```css
.alert-light {
	color:#fff;
	background-color:#f8f9fa;
	border-color:#f8f9fa;
}
```
