### ISSUE TITLE
sc-alert classes wrong colors

### ISSUE THREAD

**Issue by fugo** [pmoreno-rodriguez/grav-theme-mundana#16]
I found some wrong colors in the ``sc-alert`` css codes.   
the class ``.alert-white`` is bad and ``.alert-primary`` is the same as ``.alert-success``. 

Here is an excerpt from the ``theme.css`` file and my suggestions:
 
```css
.alert-primary {
	color:#fff;
	background-color:#28a745;   /* same as success – better #2943E6   */
	border-color:#28a745;       /* same as success – better #2943E6   */
}
.alert-primary hr {
	border-top-color:#038f6a;   /* same as success – better #5367e0   */
}

.alert-success {
	color:#fff;
	background-color:#28a745;
	border-color:#28a745;
}

.alert-white {
	color:#fff;                /* white on white - better #000 */
	background-color:white;
	border-color:white;
}
.alert-white hr {
	border-top-color:#f2f2f2;
}
.alert-white .alert-link {
	color:#e6e6e6;              /* better #333 */
}

.alert-lightblue {
	color:#fff;                 /* white too bright - better #000 */
	background-color:#e8f3ec;   /* better #adc8e6 */
	border-color:#e8f3ec;       /* better #adc8e6 */
}
.alert-lightblue hr {
	border-top-color:#d7eade;   /* better #7d93ad */
}
.alert-lightblue .alert-link {
	color:#e6e6e6;              /* better #333 */
}	
```

btw your ``/assets/css/`` has a file ``custom.css``, when you update the theme the existing ``custom.css`` will be overwriten with the new **empty** file.  
Better to use a name like ``custom.css.example`` .  
Yes – I know, always  backup before update :smile: 

I use the latest version of Mundana.  
Thank you for this nice and usefull theme.
